//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TolkesentralenLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fil
    {
        public int filID { get; set; }
        public int size { get; set; }
        public string type { get; set; }
        public Nullable<int> oppdrag_oppdragsID { get; set; }
        public Nullable<int> Oversettelse_oppdragsID { get; set; }
    
        public virtual Oppdrag Oppdrag { get; set; }
        public virtual Oppdrag Oppdrag1 { get; set; }
    }
}
