//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TolkesentralenLH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TolkesentralenDbEntities1 : DbContext
    {
        public TolkesentralenDbEntities1()
            : base("name=TolkesentralenDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Fil> Fils { get; set; }
        public virtual DbSet<Oppdrag> Oppdrags { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Poststed> Poststeds { get; set; }
        public virtual DbSet<Spraak> Spraaks { get; set; }
    }
}
