//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TolkesentralenLH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oppdrag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oppdrag()
        {
            this.Fils = new HashSet<Fil>();
            this.Fils1 = new HashSet<Fil>();
        }
    
        public int oppdragsID { get; set; }
        public string oppdragType { get; set; }
        public string oppdragsgiver { get; set; }
        public string språkFra { get; set; }
        public string språkTil { get; set; }
        public Nullable<int> fremmaateNr { get; set; }
        public string oppdragsAddres { get; set; }
        public Nullable<System.DateTime> dato { get; set; }
        public Nullable<System.DateTime> tidFra { get; set; }
        public Nullable<System.DateTime> tidTil { get; set; }
        public string frist { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> kunde_persId { get; set; }
        public Nullable<int> Tolk_persId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fil> Fils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fil> Fils1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
