//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TolkesentralenLH
{
    using Models;
    using System;
    using System.Collections.Generic;

    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Oppdrags = new HashSet<Oppdrag>();
            this.Oppdrags1 = new HashSet<Oppdrag>();
            this.Spraaks = new HashSet<Spraak>();
        }
    
        public int persId { get; set; }
        public string fornavn { get; set; }
        public string etternavn { get; set; }
        public string email { get; set; }
        public string adresse { get; set; }
        public System.DateTime regDato { get; set; }
        public string password { get; set; }
        public string kundeNr { get; set; }
        public string adminNr { get; set; }
        public string tolkNr { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> poststed_postNr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oppdrag> Oppdrags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oppdrag> Oppdrags1 { get; set; }
        public virtual Poststed Poststed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spraak> Spraaks { get; set; }
    }
}
